name: "Monitor .NET 8.0 Base Image"
on:
  workflow_dispatch:
  schedule: 
  # sundays at midnight
  - cron: "0 0 * * 0" 

# needed to trigger 'base-image-update' repository_dispatch (starts other workflows)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: mthalman/docker-bump-action@v0
        with:
          base-image-name: 'mcr.microsoft.com/dotnet/aspnet:8.0'
          target-image-name: 'ghcr.io/lancemccarthy/aspirebase:8.0'
