name: "Update Custom Base Images"
on:
  workflow_dispatch:
  repository_dispatch:
    types: [base-image-update]

env:
  CONTAINER_REGISTRY: "ghcr.io"
  BASE_IMAGE: "ghcr.io/lancemccarthy/aspirebase:8.0"
  APP_IMAGE_NAME: lancemccarthy/aspireapiservice
  APP_IMAGE_TAG: "8.0"

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  ghcr_custom_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ${{env.CONTAINER_REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    # Build a custom base image with needed Linux dependencies preinstalled
    - name: Build Custom Image and push to GitHub packages
      working-directory: '.dockerbuilds/baseimage'
      id: build-and-publish
      run: |
        docker build -t "${{env.BASE_IMAGE}}" -f Dockerfile .
        docker push "${{env.BASE_IMAGE}}"