name: "Update and Publish Custom Base Images"
on:
  workflow_dispatch:
  repository_dispatch:
    types: [base-image-update]

env:
  CONTAINER_REGISTRY: "ghcr.io"
  BASE_IMAGE: "ghcr.io/lancemccarthy/aspirebase:8.0"
  APP_IMAGE_NAME: lancemccarthy/aspireapiservice
  APP_IMAGE_TAG: "8.0"

jobs:
  ghcr_custom_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ${{env.CONTAINER_REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push to Github image repository
      uses: docker/build-push-action@v5
      with:
        context: '.dockerbuilds/baseimage'
        platforms: linux/arm64,linux/amd64
        push: true
        tags: |
          "${{env.APP_IMAGE_NAME}}"