name: "Update Custom Base Image"
on:
  workflow_dispatch:
  repository_dispatch:
    types: [base-image-update]

jobs:
  produce_custom_base_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Get package metadata from Docker Hub
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: lancemccarthy/aspirebase

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: '.dockerbuilds/baseimage'
        platforms: linux/arm64,linux/amd64
        push: true
        tags: |
          lancemccarthy/aspirebase:8.0